### ISSUE TITLE
The "Linux" installer is really a "Debian-like" installer

### ISSUE THREAD

**Issue by nagisa** [PinguinoIDE/pinguino-installers#12]
What the title says.

The installer is strictly debian-oriented and won’t work anywhere but debian.

The README should explicitly say so and point users to instructions to manually building thing on distributions that aren’t Debian or Debian-derived.

**Comment by nagisa** [comment]
No instructions to build any of the projects (-libraries, -ide) are to be seen.

**Comment by MefhigosetH** [comment]
Dear @nagisa , thanks for your contact.

I would try to update the GNU/Linux installer doc soon.

Keep this tk open until the doc is in place.

**Comment by MefhigosetH** [comment]
Hi there,

We have new GNU/Linux installer ! Please, give a try if you. Feedback would be appreciated too.
