### ISSUE TITLE
Trying to install Pinguino IDE, error NSIS Script

### ISSUE THREAD

**Issue by fpeixeiro** [PinguinoIDE/pinguino-installers#15]
Hello,
I have a win7 ultimate 64bits, and i'm trying to install. Little or almost no info at all about the steps to take to install Pinguino IDE.
I've downloaded NSIS installer (v3.06.1), installed the plugins, or at least i think i did... When i run the script, it stops with error:

MakeNSIS v3.06.1 - Copyright 1999-2020 Contributors
See the file COPYING for license details.
Credits can be found in the Users Manual.

Processing config: C:\Program Files (x86)\NSIS\nsisconf.nsh
Processing default plugins: "C:\Program Files (x86)\NSIS\Plugins\x86-ansi\*.dll"
 + Banner::destroy
 + Banner::getWindow
 + Banner::show
 + BgImage::AddImage
 + BgImage::AddText
 + BgImage::Clear
 + BgImage::Destroy
 + BgImage::Redraw
 + BgImage::SetBg
 + BgImage::SetReturn
 + BgImage::Sound
 + Dialer::AttemptConnect
 + Dialer::AutodialHangup
 + Dialer::AutodialOnline
 + Dialer::AutodialUnattended
 + Dialer::GetConnectedState
 + InstallOptions::dialog
 + InstallOptions::initDialog
 + InstallOptions::show
 + LangDLL::LangDialog
 + Math::Script
 + StartMenu::Init
 + StartMenu::Select
 + StartMenu::Show
 + System::Alloc
 + System::Call
 + System::Copy
 + System::Free
 + System::Get
 + System::Int64Op
 + System::Store
 + System::StrAlloc
 + TypeLib::GetLibVersion
 + TypeLib::Register
 + TypeLib::UnRegister
 + UserInfo::GetAccountType
 + UserInfo::GetName
 + UserInfo::GetOriginalAccountType
 + VPatch::GetFileCRC32
 + VPatch::GetFileMD5
 + VPatch::vpatchfile
 + advsplash::show
 + nsDialogs::Create
 + nsDialogs::CreateControl
 + nsDialogs::CreateItem
 + nsDialogs::CreateTimer
 + nsDialogs::GetUserData
 + nsDialogs::KillTimer
 + nsDialogs::OnBack
 + nsDialogs::OnChange
 + nsDialogs::OnClick
 + nsDialogs::OnNotify
 + nsDialogs::SelectFileDialog
 + nsDialogs::SelectFolderDialog
 + nsDialogs::SetRTL
 + nsDialogs::SetUserData
 + nsDialogs::Show
 + nsExec::Exec
 + nsExec::ExecToLog
 + nsExec::ExecToStack
 + nsisdl::download
 + nsisdl::download_quiet
 + splash::show

!define: "MUI_INSERT_NSISCONF"=""

Changing directory to: "G:\Temp"

Processing script file: "G:\Temp\pinguino-installer.nsi" (UTF16LE)
XPStyle: on
SetDatablockOptimize: on
SetCompress: force
SetCompressor: /SOLID lzma
ShowInstDetails: show
!include: "C:\Program Files (x86)\NSIS\Include\WinMessages.nsh" (ACP)
!define: "WINMESSAGES_INCLUDED"=""
!include: closed: "C:\Program Files (x86)\NSIS\Include\WinMessages.nsh"
!include: "C:\Program Files (x86)\NSIS\Include\MUI2.nsh" (ACP)
!include: "C:\Program Files (x86)\NSIS\Contrib\Modern UI 2\MUI2.nsh" (ACP)
NSIS Modern User Interface version 2.1 - Copyright 2002-2020 Joost Verburg (C:\Program Files (x86)\NSIS\Contrib\Modern UI 2\MUI2.nsh:14)
!include: closed: "C:\Program Files (x86)\NSIS\Contrib\Modern UI 2\MUI2.nsh"
!include: closed: "C:\Program Files (x86)\NSIS\Include\MUI2.nsh"
!include: "C:\Program Files (x86)\NSIS\Include\FileFunc.nsh" (ACP)
!include: closed: "C:\Program Files (x86)\NSIS\Include\FileFunc.nsh"
!include: "C:\Program Files (x86)\NSIS\Include\WinVer.nsh" (ACP)
!include: closed: "C:\Program Files (x86)\NSIS\Include\WinVer.nsh"
!include: "C:\Program Files (x86)\NSIS\Include\nsDialogs.nsh" (ACP)
!include: closed: "C:\Program Files (x86)\NSIS\Include\nsDialogs.nsh"
!include: "C:\Program Files (x86)\NSIS\Include\LogicLib.nsh" (ACP)
!include: closed: "C:\Program Files (x86)\NSIS\Include\LogicLib.nsh"
!include: "C:\Program Files (x86)\NSIS\Include\x64.nsh" (ACP)
!define: "___X64__NSH___"=""
!include: "C:\Program Files (x86)\NSIS\Include\LogicLib.nsh" (ACP)
!include: closed: "C:\Program Files (x86)\NSIS\Include\LogicLib.nsh"
!define: "IsWow64"=""" IsWow64 """
!define: "RunningX64"=""" RunningX64 """
!define: "GetNativeMachineArchitecture"="!insertmacro GetNativeMachineArchitecture "
!define: "IsNativeMachineArchitecture"=""" IsNativeMachineArchitecture "
!define: "IsNativeIA32"=""" IsNativeMachineArchitecture  332"
!define: "IsNativeAMD64"=""" IsNativeMachineArchitecture  34404"
!define: "IsNativeARM64"=""" IsNativeMachineArchitecture  43620"
!define: "DisableX64FSRedirection"="!insertmacro DisableX64FSRedirection"
!define: "EnableX64FSRedirection"="!insertmacro EnableX64FSRedirection"
!include: closed: "C:\Program Files (x86)\NSIS\Include\x64.nsh"
!define: "PINGUINO_NAME"="Pinguino"
!define: "PINGUINO_VERSION"="13"
!define: "INSTALLER_VERSION"="1.8.0.0"
!define: "LIBUSBWIN32_VERSION"="1.2.6.0"
!define: "GIT_VERSION"="2.20.1"
!define: "PYTHON_MAJOR_VERSION"="3"
!define: "PYTHON_MINOR_VERSION"="7"
!define: "PYTHON_PATCH_VERSION"="7"
!define: "PYTHON_SHORT_VERSION"="3.7"
!define: "PYTHON_VERSION"="3.7.7"
!define: "PINGUINO_ICON"="pinguino11.ico"
!define: "PINGUINO_BMP"="pinguino11.bmp"
!define: "INSTALLER_NAME"="Pinguino-installer"
!define: "FILE_OWNER"="Pinguino"
!define: "FILE_URL"="http://www.pinguino.cc"
!define: "CURL"="curl.exe"
!define: "PBS_MARQUEE"="0x08"
!define: "MUI_ABORTWARNING"=""
!define: "MUI_INSTFILESPAGE_PROGRESSBAR"="smooth"
!define: "MUI_INSTFILESPAGE_COLORS"="00FF00 000000 "
!define: "MUI_ICON"="pinguino11.ico"
!define: "MUI_UNICON"="pinguino11.ico"
!define: "MUI_WELCOMEFINISHPAGE_BITMAP"="pinguino11.bmp"
!define: "MUI_UNWELCOMEFINISHPAGE_BITMAP"="pinguino11.bmp"
!define: "MUI_FINISHPAGE_NOAUTOCLOSE"=""
!define: "MUI_FINISHPAGE_RUN"=""
!define: "MUI_FINISHPAGE_RUN_NOTCHECKED"=""
!define: "MUI_FINISHPAGE_RUN_TEXT"="Start Pinguino"
!define: "MUI_FINISHPAGE_RUN_FUNCTION"="LaunchPinguinoIDE"
!define: "MUI_FINISHPAGE_SHOWREADME_NOTCHECKED"=""
!define: "REG_UNINSTALL"="SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Pinguino"
!define: "REG_PINGUINO"="SOFTWARE\Pinguino"
!define: "REG_XC8"="SOFTWARE\Microchip\MPLAB XC8 C Compiler"
!define: "REG_PYTHON"="SOFTWARE\Python\PythonCore\3.7\InstallPath"
!define: "REG_GIT"="SOFTWARE\GitForWindows"
!define: "REG_USERDOC"="SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders"
!define: "URL_SOURCEFORGE"="https://sourceforge.net/projects"
!define: "URL_GITHUB"="https://github.com/PinguinoIDE"
!define: "URL_PINGUINO"="https://sourceforge.net/projects/pinguinoide/files"
!define: "URL_SFOS"="https://sourceforge.net/projects/pinguinoide/files/windows"
!define: "URL_MCHP"="http://www.microchip.com"
!define: "URL_LIBUSB"="https://sourceforge.net/projects/libusb-win32/files/libusb-win32-releases"
!define: "URL_PYTHON"="https://www.python.org/ftp/python"
!define: "URL_GIT"="https://github.com/git-for-windows/git/releases/download"
!define: "URL_VISUALCPP"="https://aka.ms/vs/16/release/"
!define: "pinguino-ide"="pinguino-ide-master.zip"
!define: "pinguino-libraries"="pinguino-libraries.zip"
!define: "pinguino-xc8"="xc8-v$xc8_version-full-install-windows-installer.exe"
!define: "pinguino-xc8-latest"="mplabxc8windows"
!define: "pinguino-sdcc32"="pinguino-windows32-sdcc-mpic16.zip"
!define: "pinguino-sdcc64"="pinguino-windows64-sdcc-mpic16.zip"
!define: "pinguino-gcc32"="pinguino-windows32-gcc-mips-elf.zip"
!define: "pinguino-gcc64"="pinguino-windows64-gcc-mips-elf.zip"
Name: "Pinguino"
InstallDir: "C:\Pinguino"
OutFile: "Pinguino-installer-v1.8.0.0.exe"
BrandingText: "http://www.pinguino.cc"
VIAddVersionKey: "ProductName" "Pinguino-installer"
VIAddVersionKey: "ProductVersion" "1.8.0.0"
VIAddVersionKey: "CompanyName" "Pinguino"
VIAddVersionKey: "LegalCopyright" "2014-2020 Pinguino"
VIAddVersionKey: "FileDescription" "Pinguino IDE & Compilers Installer"
VIAddVersionKey: "FileVersion" "1.8.0.0"
!insertmacro: MUI_PAGE_WELCOME
Error while loading icon from "pinguino11.ico": can't open file
Error in macro MUI_INTERFACE on macroline 87
Error in macro MUI_PAGE_INIT on macroline 7
Error in macro MUI_PAGE_WELCOME on macroline 5
Error in script "G:\Temp\pinguino-installer.nsi" on line 138 -- aborting creation process

So what am I doing wrong?

Thanks.
Fernando Peixeiro

**Comment by MefhigosetH** [comment]
Dear @fpeixeiro , thanks for your contact.

Please, check the following:

* Check the privileges of your current user. Try to execute the installer as Administrator.

* The installer is on G: drive? Try move the installer to C: somewhere, before execute it.

* Try another version of installer. Check the v1.7.1.4 here https://github.com/PinguinoIDE/pinguino-installers/releases/tag/2020.03.14-STABLE

We are working on a new installer, but it's not ready Yet.

Cheers

**Comment by fpeixeiro** [comment]
Hello Victor,
Thanks for the prompt reply.

I was running with the admin acount.
I tryed to execute from c:, same error, last 5 lines are equal and the rest a think is the same.

Error while loading icon from "pinguino11.ico": can't open file
Error in macro MUI_INTERFACE on macroline 87
Error in macro MUI_PAGE_INIT on macroline 7
Error in macro MUI_PAGE_WELCOME on macroline 5
Error in script "C:\pinguino-installer.nsi" on line 138 -- aborting creation process

I tried diferent locations in C:, always the same error:

Error while loading icon from "pinguino11.ico": can't open file
Error in macro MUI_INTERFACE on macroline 87
Error in macro MUI_PAGE_INIT on macroline 7
Error in macro MUI_PAGE_WELCOME on macroline 5
Error in script "C:\Program Files (x86)\pinguino-installer.nsi" on line 138 -- aborting creation process

Thanks,
Fernando Peixeiro

**Comment by MefhigosetH** [comment]
Hi there,

Sory for the delay. It's seem that the compiler not found the .ico file.

```
Error while loading icon from "pinguino11.ico": can't open file.
```

You need to clone all the repo to succesfully compile the NSIS script, and install some plugins that exists on a folder, inside this repo.

I know, I need a good README.md with the instructions yo compile this script :-(

In a few weeks, I would make a new version of this Windows installer for Pinguino IDE v13 + Python3.

Please, stay tunned.
