### ISSUE TITLE
Linux ElementaryOS Installing

### ISSUE THREAD

**Issue by AngelPortal** [PinguinoIDE/pinguino-installers#16]
I was trying to install the IDE on elementaryOS. Everything went ok, but I noticed that is using python 2.7 that is deprecated.
I also noticed that it was only possible to install Version 12. Version 11 is not working.
The version 12 dos not open any project. 
I have the latest version of elemetary OS.

**Comment by MefhigosetH** [comment]
Dear @AngelPortal , thanks for your contact.

The current version of Pinguino IDE is v13 and you can find it's cose, on the branch with the same name.

This version is based on Python3 (I've tested on a Ubuntu 20.04 LTS + Python 3.8, and I've been able to open the blink example, compile it and upload to a PIC2550 board succesfully).

We haven't an installer for GNU/Linux yet. But I plan publish a manual install guide on the Pingüino Website.

Cheers

**Comment by MefhigosetH** [comment]
Hi there,

We have new GNU/Linux installer ! Please, give a try if you. Feedback would be appreciated too.
