### ISSUE TITLE
Compatibility with newer distros [Solved]

### ISSUE THREAD

**Issue by luzemario** [PinguinoIDE/pinguino-installers#17]
Hello folks,

install script brought me several errors on Ubuntu 20.04. There is Qt5 instead QT4, and there is no "pip", since versions of Python before 3 are deprecated (so there is only pip3 program).

Some of the errors found:

``` /usr/bin/python: No module named pip
touch: não foi possível tocar '/opt/pinguino/v12/pinguino/qtgui/config/pinguino.linux.conf': Arquivo ou diretório não encontrado
./pinguino-installer-v1.3.3.sh: linha 447: /opt/pinguino/v12/pinguino/qtgui/config/pinguino.linux.conf: Arquivo ou diretório não encontrado
./pinguino-installer-v1.3.3.sh: linha 448: /opt/pinguino/v12/pinguino/qtgui/config/pinguino.linux.conf: Arquivo ou diretório não encontrado
./pinguino-installer-v1.3.3.sh: linha 449: /opt/pinguino/v12/pinguino/qtgui/config/pinguino.linux.conf: Arquivo ou diretório não encontrado
./pinguino-installer-v1.3.3.sh: linha 451: /opt/pinguino/v12/pinguino/qtgui/config/pinguino.linux.conf: Arquivo ou diretório não encontrado
./pinguino-installer-v1.3.3.sh: linha 453: /opt/pinguino/v12/pinguino/qtgui/config/pinguino.linux.conf: Arquivo ou diretório não encontrado
./pinguino-installer-v1.3.3.sh: linha 454: /opt/pinguino/v12/pinguino/qtgui/config/pinguino.linux.conf: Arquivo ou diretório não encontrado
./pinguino-installer-v1.3.3.sh: linha 455: /opt/pinguino/v12/pinguino/qtgui/config/pinguino.linux.conf: Arquivo ou diretório não encontrado
./pinguino-installer-v1.3.3.sh: linha 456: /opt/pinguino/v12/pinguino/qtgui/config/pinguino.linux.conf: Arquivo ou diretório não encontrado
./pinguino-installer-v1.3.3.sh: linha 458: /opt/pinguino/v12/pinguino/qtgui/config/pinguino.linux.conf: Arquivo ou diretório não encontrado

python: can't open file '/opt/pinguino/v12/pinguino-ide.py': [Errno 2] No such file or directory ```

**Comment by luzemario** [comment]
"Arquivo ou diretório não encontrado" means "File or directory not found".

**Comment by MefhigosetH** [comment]
Dear @luzemario ,

The install script is not recommended right now. Need some develop yet. And the current version of PinguinoIDE is v13, thats works with Python3 as Python2 is now End-of-Life.

I suggest you try install manually. I have on my laptop Ubuntu 20.04 LTS, and PinguinoIDE v13, and open fine, compile and upload Blink example on a PIC2550 board.

This weekend I upload to the website instructions to achieve this manually.

In the mean time, my pinguino.linux.conf is this:

```
[Paths]
sdcc_bin = /opt/pinguino/p8/bin
gcc_bin  = /opt/pinguino/p32/bin
xc8_bin  = /opt/microchip/xc8/v1.38/bin
pinguino_8_libs = /opt/pinguino/pinguino-libraries-master/p8
pinguino_32_libs = /opt/pinguino/pinguino-libraries-master/p32
user_libs = /opt/pinguino/v13/pinguinolibs

install_path = /opt/pinguino/v13
user_path = ~/Pinguino/v13
```

Change to your own paths.

Tell me if this works for you.

Don't forget download the `pinguino-libraries` and `pinguino-compilers` packages. XC8 is optional. I don't have XC8 in my laptop and the IDE compiles fine.

Welcome to the community and thanks for your question.

Best regardas, from Buenos Aires.

**Comment by luzemario** [comment]
> 
> I suggest you try install manually. I have on my laptop Ubuntu 20.04 LTS, and PinguinoIDE v13, and open fine, compile and upload Blink example on a PIC2550 board.
> 
> This weekend I upload to the website instructions to achieve this manually.
> 
>

Thanks for your quick reply. I will try it out. This project is awesome.

Greetings from Brazil.

**Comment by MefhigosetH** [comment]
Hi there,

We have new GNU/Linux installer ! Please, give a try if you. Feedback would be appreciated too.

**Comment by luzemario** [comment]
> Hi there,
> 
> We have new GNU/Linux installer ! Please, give a try if you. Feedback would be appreciated too.

Hi, @MefhigosetH, the installer ran flawlessly, all dependencies were met and Pinguino IDE opened like a charm... ;-)

I guess most Ubuntu-based distros that come with default Python3 will have no issues with the new installer.

You can close this issue.

**Comment by MefhigosetH** [comment]
Dear @luzemario ,

Thanks for your feedback and the time you invest on testing. It's important to the project.

Best regards.
