### ISSUE TITLE
USB error on upload to pinguino board

### ISSUE THREAD

**Issue by PaulCElliott** [PinguinoIDE/pinguino-installers#19]
Rule needs to be added to etc/udev/rules.d to allow access by ide to usb device.
Running ubuntu 20.4 pinguino V13 installed with installer_v2.sh
added SUBSYSTEM=="usb", ATTR{idVendor}=="04d8", ATTR{idProduct}=="003c", MODE="0666"
and system then worked OK

**Comment by MefhigosetH** [comment]
Dear @PaulCElliott , we appreciated this info. We will add this comment to the documentatio o the installer itself.

Sory for the delay... Keep the good work. Cheers.
