### ISSUE TITLE
Not found: /usr/bin/p32-gcc

### ISSUE THREAD

**Issue by jcorredorc** [PinguinoIDE/pinguino-installers#7]
Hi,  Thanks for the install-script for macosx,

I finally install de IDE following the instructions on the script. Nevertheless, I was wondering if the libraries and the compiler are configured just  for 8 bit microcontrollers because when I try to compile the blink example for a 32 bit board (PIC32-Pinguino-OTG) a warning is shown: "Impossible to compile this file, missing libraries and/or compiler". 

Could you include the required files ? or give some advice in order to include this files into the proper directory---or to build the compiler---(I find the available compiler for macosx, but I don't know how make it work). 

Thanks in advance, 
Best regards

**Comment by sanzor** [comment]
I have the same problem

**Comment by rblanchot** [comment]
Click on IDE > Tools > Path to enable the Path tab on the right of the Pinguino IDE window.
Check the path to the 32-bit compiler. If it's not the right one, uncheck the "Use default paths" and update the p32-gcc path. The compiler is usually in /opt/pinguino/p32.

**Comment by MefhigosetH** [comment]
I will close this issue because it's age.
